version: '3.8'
services:
  app:
    build: .
    ports:
      - "8084:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=myapp_db
      - DB_USER=root
      - DB_PASS=password
  db:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products_db
      MYSQL_USER: usuario_app
      MYSQL_PASS: clave_app
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: