version: '3.8'
services:
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/local/products.sql:/docker-entrypoint-initdb.d/products.sql
  app:
    volumes:
      - ./:/var/www/html